# Generated by Django 3.2 on 2022-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('image', models.URLField(verbose_name='Изображение товара')),
                ('category', models.CharField(choices=[('other', 'разное'), ('smartphone', 'смартфоны'), ('clothes', 'одежда'), ('home', 'для дома'), ('computers', 'компьютеры')], default='other', max_length=10, verbose_name='Категория товара')),
                ('remainder', models.IntegerField(verbose_name='Остаток от товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость товара')),
            ],
        ),
    ]
