# Generated by Django 3.2 on 2022-10-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(verbose_name='Остаток от товара'),
        ),
    ]
