# Generated by Django 3.2 on 2022-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'разное'), ('smartphone', 'смартфоны'), ('clothes', 'одежда'), ('home', 'товары для дома'), ('computers', 'компьютеры')], default='other', max_length=10, verbose_name='Категория товара'),
        ),
    ]
