# Generated by Django 3.2 on 2022-10-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='AddToCart',
        ),
    ]
