# Generated by Django 3.2 on 2022-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_cart_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество в корзине'),
        ),
    ]
